//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Input/InputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputActions : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputActions"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""ca8b878a-4923-4210-a66e-f14dd8f72edd"",
            ""actions"": [
                {
                    ""name"": ""Axis"",
                    ""type"": ""Value"",
                    ""id"": ""5984395b-9aab-4d76-a036-af08f2467107"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""SouthButton"",
                    ""type"": ""Button"",
                    ""id"": ""6773d853-6828-449d-8150-61b5a2c8fd35"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""NorthButton"",
                    ""type"": ""Button"",
                    ""id"": ""3f5762b7-109c-4646-bef4-ff0db816942a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""EastButton"",
                    ""type"": ""Button"",
                    ""id"": ""f2c99eb8-f6ca-43e9-9d1e-6921b10dbaa5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""WestButton"",
                    ""type"": ""Button"",
                    ""id"": ""f17f9563-3d27-4bf4-80f9-1b16326bb75a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Pause"",
                    ""type"": ""Button"",
                    ""id"": ""64d650b6-cc07-4782-a448-90189b4c5277"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RBumper"",
                    ""type"": ""Button"",
                    ""id"": ""b6b1f3e1-ef74-403d-a2b8-8cdfd1610d26"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LBumper"",
                    ""type"": ""Button"",
                    ""id"": ""7a9b1b56-c547-4563-a9e4-412464c17a99"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RTrigger"",
                    ""type"": ""Button"",
                    ""id"": ""3cd5e41e-a630-4ca0-a21c-b3f0d0c2ca04"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LTrigger"",
                    ""type"": ""Button"",
                    ""id"": ""33db86a8-c554-46ac-b820-1295a1c384cf"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""57f8cb3d-2ce9-4e00-be6e-4ce600675521"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Axis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dabd6449-de7b-480f-9fbc-eb5756cb655b"",
                    ""path"": ""<Gamepad>/dpad"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Axis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""08f22ccd-5df0-41b5-b951-9405d877a1a0"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SouthButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9c6e3143-a93f-4216-a671-58b409368e18"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NorthButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""aeaecc27-e994-4610-86a8-f97681555d06"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""EastButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""90252417-b0c4-4c21-ba75-57aa3ba95a3a"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""WestButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""60791cd6-606b-41e9-a3eb-ca51b05d1995"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""be0b0dc6-d763-4f4a-a1c0-31bcdc6e55a6"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RBumper"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""35a65465-7a6a-4710-91df-a322e206b8d3"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LBumper"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""86a924e1-b3d8-4bd9-9734-ca4308e1e7d3"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RTrigger"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""795e5be0-5fb3-4691-874d-7c81eab63247"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LTrigger"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Player1"",
            ""id"": ""5d673996-4e70-4dda-b01f-776d7c36e553"",
            ""actions"": [
                {
                    ""name"": ""Axis"",
                    ""type"": ""Value"",
                    ""id"": ""ca633ca8-8dca-4ed7-a264-150bc07b4aeb"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""SouthButton"",
                    ""type"": ""Button"",
                    ""id"": ""4200f0ae-f021-4c5d-97d8-0042cf2d279b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""NorthButton"",
                    ""type"": ""Button"",
                    ""id"": ""078dda51-c512-4b98-9fb2-168bb8d2d646"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""EastButton"",
                    ""type"": ""Button"",
                    ""id"": ""09c4d181-8086-4aad-8981-f29f5426416d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""WestButton"",
                    ""type"": ""Button"",
                    ""id"": ""56f6f660-8b0f-4021-ad30-64a1b12e37d1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Pause"",
                    ""type"": ""Button"",
                    ""id"": ""6bc537dd-4356-442c-89c2-daf6f1f94ce9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RBumper"",
                    ""type"": ""Button"",
                    ""id"": ""ea4eb7c2-4292-4109-97f6-c7c29aa260b6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LBumper"",
                    ""type"": ""Button"",
                    ""id"": ""c28efaaf-a8d9-4e74-a58e-99016ccdc361"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RTrigger"",
                    ""type"": ""Button"",
                    ""id"": ""57f11384-1c47-4cbb-a7c2-dca428a83f48"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LTrigger"",
                    ""type"": ""Button"",
                    ""id"": ""ba2d57c1-2b19-4c78-b29e-7cfbc6f4bb2c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""fe02adaa-88bc-4ee6-ae9e-9fe7d5531f8b"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Axis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""732501ba-8226-46c5-a3dc-1ec083329a62"",
                    ""path"": ""<Gamepad>/dpad"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Axis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f094fbdb-2cbc-438e-813c-f4dd998962fa"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SouthButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""eced4613-6a37-4238-b31d-94e5a9e3804a"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NorthButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""89425a1e-d0d4-4149-a84f-0e941153088e"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""EastButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""185bb1da-1a2f-4360-bf56-5346f9f1c9c1"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""WestButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""25e21ff1-de3c-47db-8218-e949994643da"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""35225ab0-1f3a-4a97-bdc5-ad345c47d41f"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RBumper"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""de3ad342-61e1-40d4-abfa-97da7a7732e8"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LBumper"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""27e9d52a-614a-4381-bdcd-c0ba22bb878a"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RTrigger"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d03f310d-9304-4f66-a951-182dbb6c07ba"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LTrigger"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_Axis = m_Player.FindAction("Axis", throwIfNotFound: true);
        m_Player_SouthButton = m_Player.FindAction("SouthButton", throwIfNotFound: true);
        m_Player_NorthButton = m_Player.FindAction("NorthButton", throwIfNotFound: true);
        m_Player_EastButton = m_Player.FindAction("EastButton", throwIfNotFound: true);
        m_Player_WestButton = m_Player.FindAction("WestButton", throwIfNotFound: true);
        m_Player_Pause = m_Player.FindAction("Pause", throwIfNotFound: true);
        m_Player_RBumper = m_Player.FindAction("RBumper", throwIfNotFound: true);
        m_Player_LBumper = m_Player.FindAction("LBumper", throwIfNotFound: true);
        m_Player_RTrigger = m_Player.FindAction("RTrigger", throwIfNotFound: true);
        m_Player_LTrigger = m_Player.FindAction("LTrigger", throwIfNotFound: true);
        // Player1
        m_Player1 = asset.FindActionMap("Player1", throwIfNotFound: true);
        m_Player1_Axis = m_Player1.FindAction("Axis", throwIfNotFound: true);
        m_Player1_SouthButton = m_Player1.FindAction("SouthButton", throwIfNotFound: true);
        m_Player1_NorthButton = m_Player1.FindAction("NorthButton", throwIfNotFound: true);
        m_Player1_EastButton = m_Player1.FindAction("EastButton", throwIfNotFound: true);
        m_Player1_WestButton = m_Player1.FindAction("WestButton", throwIfNotFound: true);
        m_Player1_Pause = m_Player1.FindAction("Pause", throwIfNotFound: true);
        m_Player1_RBumper = m_Player1.FindAction("RBumper", throwIfNotFound: true);
        m_Player1_LBumper = m_Player1.FindAction("LBumper", throwIfNotFound: true);
        m_Player1_RTrigger = m_Player1.FindAction("RTrigger", throwIfNotFound: true);
        m_Player1_LTrigger = m_Player1.FindAction("LTrigger", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private IPlayerActions m_PlayerActionsCallbackInterface;
    private readonly InputAction m_Player_Axis;
    private readonly InputAction m_Player_SouthButton;
    private readonly InputAction m_Player_NorthButton;
    private readonly InputAction m_Player_EastButton;
    private readonly InputAction m_Player_WestButton;
    private readonly InputAction m_Player_Pause;
    private readonly InputAction m_Player_RBumper;
    private readonly InputAction m_Player_LBumper;
    private readonly InputAction m_Player_RTrigger;
    private readonly InputAction m_Player_LTrigger;
    public struct PlayerActions
    {
        private @InputActions m_Wrapper;
        public PlayerActions(@InputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Axis => m_Wrapper.m_Player_Axis;
        public InputAction @SouthButton => m_Wrapper.m_Player_SouthButton;
        public InputAction @NorthButton => m_Wrapper.m_Player_NorthButton;
        public InputAction @EastButton => m_Wrapper.m_Player_EastButton;
        public InputAction @WestButton => m_Wrapper.m_Player_WestButton;
        public InputAction @Pause => m_Wrapper.m_Player_Pause;
        public InputAction @RBumper => m_Wrapper.m_Player_RBumper;
        public InputAction @LBumper => m_Wrapper.m_Player_LBumper;
        public InputAction @RTrigger => m_Wrapper.m_Player_RTrigger;
        public InputAction @LTrigger => m_Wrapper.m_Player_LTrigger;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void SetCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterface != null)
            {
                @Axis.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnAxis;
                @Axis.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnAxis;
                @Axis.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnAxis;
                @SouthButton.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSouthButton;
                @SouthButton.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSouthButton;
                @SouthButton.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSouthButton;
                @NorthButton.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnNorthButton;
                @NorthButton.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnNorthButton;
                @NorthButton.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnNorthButton;
                @EastButton.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnEastButton;
                @EastButton.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnEastButton;
                @EastButton.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnEastButton;
                @WestButton.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnWestButton;
                @WestButton.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnWestButton;
                @WestButton.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnWestButton;
                @Pause.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnPause;
                @Pause.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnPause;
                @Pause.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnPause;
                @RBumper.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnRBumper;
                @RBumper.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnRBumper;
                @RBumper.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnRBumper;
                @LBumper.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLBumper;
                @LBumper.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLBumper;
                @LBumper.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLBumper;
                @RTrigger.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnRTrigger;
                @RTrigger.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnRTrigger;
                @RTrigger.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnRTrigger;
                @LTrigger.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLTrigger;
                @LTrigger.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLTrigger;
                @LTrigger.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLTrigger;
            }
            m_Wrapper.m_PlayerActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Axis.started += instance.OnAxis;
                @Axis.performed += instance.OnAxis;
                @Axis.canceled += instance.OnAxis;
                @SouthButton.started += instance.OnSouthButton;
                @SouthButton.performed += instance.OnSouthButton;
                @SouthButton.canceled += instance.OnSouthButton;
                @NorthButton.started += instance.OnNorthButton;
                @NorthButton.performed += instance.OnNorthButton;
                @NorthButton.canceled += instance.OnNorthButton;
                @EastButton.started += instance.OnEastButton;
                @EastButton.performed += instance.OnEastButton;
                @EastButton.canceled += instance.OnEastButton;
                @WestButton.started += instance.OnWestButton;
                @WestButton.performed += instance.OnWestButton;
                @WestButton.canceled += instance.OnWestButton;
                @Pause.started += instance.OnPause;
                @Pause.performed += instance.OnPause;
                @Pause.canceled += instance.OnPause;
                @RBumper.started += instance.OnRBumper;
                @RBumper.performed += instance.OnRBumper;
                @RBumper.canceled += instance.OnRBumper;
                @LBumper.started += instance.OnLBumper;
                @LBumper.performed += instance.OnLBumper;
                @LBumper.canceled += instance.OnLBumper;
                @RTrigger.started += instance.OnRTrigger;
                @RTrigger.performed += instance.OnRTrigger;
                @RTrigger.canceled += instance.OnRTrigger;
                @LTrigger.started += instance.OnLTrigger;
                @LTrigger.performed += instance.OnLTrigger;
                @LTrigger.canceled += instance.OnLTrigger;
            }
        }
    }
    public PlayerActions @Player => new PlayerActions(this);

    // Player1
    private readonly InputActionMap m_Player1;
    private IPlayer1Actions m_Player1ActionsCallbackInterface;
    private readonly InputAction m_Player1_Axis;
    private readonly InputAction m_Player1_SouthButton;
    private readonly InputAction m_Player1_NorthButton;
    private readonly InputAction m_Player1_EastButton;
    private readonly InputAction m_Player1_WestButton;
    private readonly InputAction m_Player1_Pause;
    private readonly InputAction m_Player1_RBumper;
    private readonly InputAction m_Player1_LBumper;
    private readonly InputAction m_Player1_RTrigger;
    private readonly InputAction m_Player1_LTrigger;
    public struct Player1Actions
    {
        private @InputActions m_Wrapper;
        public Player1Actions(@InputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Axis => m_Wrapper.m_Player1_Axis;
        public InputAction @SouthButton => m_Wrapper.m_Player1_SouthButton;
        public InputAction @NorthButton => m_Wrapper.m_Player1_NorthButton;
        public InputAction @EastButton => m_Wrapper.m_Player1_EastButton;
        public InputAction @WestButton => m_Wrapper.m_Player1_WestButton;
        public InputAction @Pause => m_Wrapper.m_Player1_Pause;
        public InputAction @RBumper => m_Wrapper.m_Player1_RBumper;
        public InputAction @LBumper => m_Wrapper.m_Player1_LBumper;
        public InputAction @RTrigger => m_Wrapper.m_Player1_RTrigger;
        public InputAction @LTrigger => m_Wrapper.m_Player1_LTrigger;
        public InputActionMap Get() { return m_Wrapper.m_Player1; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(Player1Actions set) { return set.Get(); }
        public void SetCallbacks(IPlayer1Actions instance)
        {
            if (m_Wrapper.m_Player1ActionsCallbackInterface != null)
            {
                @Axis.started -= m_Wrapper.m_Player1ActionsCallbackInterface.OnAxis;
                @Axis.performed -= m_Wrapper.m_Player1ActionsCallbackInterface.OnAxis;
                @Axis.canceled -= m_Wrapper.m_Player1ActionsCallbackInterface.OnAxis;
                @SouthButton.started -= m_Wrapper.m_Player1ActionsCallbackInterface.OnSouthButton;
                @SouthButton.performed -= m_Wrapper.m_Player1ActionsCallbackInterface.OnSouthButton;
                @SouthButton.canceled -= m_Wrapper.m_Player1ActionsCallbackInterface.OnSouthButton;
                @NorthButton.started -= m_Wrapper.m_Player1ActionsCallbackInterface.OnNorthButton;
                @NorthButton.performed -= m_Wrapper.m_Player1ActionsCallbackInterface.OnNorthButton;
                @NorthButton.canceled -= m_Wrapper.m_Player1ActionsCallbackInterface.OnNorthButton;
                @EastButton.started -= m_Wrapper.m_Player1ActionsCallbackInterface.OnEastButton;
                @EastButton.performed -= m_Wrapper.m_Player1ActionsCallbackInterface.OnEastButton;
                @EastButton.canceled -= m_Wrapper.m_Player1ActionsCallbackInterface.OnEastButton;
                @WestButton.started -= m_Wrapper.m_Player1ActionsCallbackInterface.OnWestButton;
                @WestButton.performed -= m_Wrapper.m_Player1ActionsCallbackInterface.OnWestButton;
                @WestButton.canceled -= m_Wrapper.m_Player1ActionsCallbackInterface.OnWestButton;
                @Pause.started -= m_Wrapper.m_Player1ActionsCallbackInterface.OnPause;
                @Pause.performed -= m_Wrapper.m_Player1ActionsCallbackInterface.OnPause;
                @Pause.canceled -= m_Wrapper.m_Player1ActionsCallbackInterface.OnPause;
                @RBumper.started -= m_Wrapper.m_Player1ActionsCallbackInterface.OnRBumper;
                @RBumper.performed -= m_Wrapper.m_Player1ActionsCallbackInterface.OnRBumper;
                @RBumper.canceled -= m_Wrapper.m_Player1ActionsCallbackInterface.OnRBumper;
                @LBumper.started -= m_Wrapper.m_Player1ActionsCallbackInterface.OnLBumper;
                @LBumper.performed -= m_Wrapper.m_Player1ActionsCallbackInterface.OnLBumper;
                @LBumper.canceled -= m_Wrapper.m_Player1ActionsCallbackInterface.OnLBumper;
                @RTrigger.started -= m_Wrapper.m_Player1ActionsCallbackInterface.OnRTrigger;
                @RTrigger.performed -= m_Wrapper.m_Player1ActionsCallbackInterface.OnRTrigger;
                @RTrigger.canceled -= m_Wrapper.m_Player1ActionsCallbackInterface.OnRTrigger;
                @LTrigger.started -= m_Wrapper.m_Player1ActionsCallbackInterface.OnLTrigger;
                @LTrigger.performed -= m_Wrapper.m_Player1ActionsCallbackInterface.OnLTrigger;
                @LTrigger.canceled -= m_Wrapper.m_Player1ActionsCallbackInterface.OnLTrigger;
            }
            m_Wrapper.m_Player1ActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Axis.started += instance.OnAxis;
                @Axis.performed += instance.OnAxis;
                @Axis.canceled += instance.OnAxis;
                @SouthButton.started += instance.OnSouthButton;
                @SouthButton.performed += instance.OnSouthButton;
                @SouthButton.canceled += instance.OnSouthButton;
                @NorthButton.started += instance.OnNorthButton;
                @NorthButton.performed += instance.OnNorthButton;
                @NorthButton.canceled += instance.OnNorthButton;
                @EastButton.started += instance.OnEastButton;
                @EastButton.performed += instance.OnEastButton;
                @EastButton.canceled += instance.OnEastButton;
                @WestButton.started += instance.OnWestButton;
                @WestButton.performed += instance.OnWestButton;
                @WestButton.canceled += instance.OnWestButton;
                @Pause.started += instance.OnPause;
                @Pause.performed += instance.OnPause;
                @Pause.canceled += instance.OnPause;
                @RBumper.started += instance.OnRBumper;
                @RBumper.performed += instance.OnRBumper;
                @RBumper.canceled += instance.OnRBumper;
                @LBumper.started += instance.OnLBumper;
                @LBumper.performed += instance.OnLBumper;
                @LBumper.canceled += instance.OnLBumper;
                @RTrigger.started += instance.OnRTrigger;
                @RTrigger.performed += instance.OnRTrigger;
                @RTrigger.canceled += instance.OnRTrigger;
                @LTrigger.started += instance.OnLTrigger;
                @LTrigger.performed += instance.OnLTrigger;
                @LTrigger.canceled += instance.OnLTrigger;
            }
        }
    }
    public Player1Actions @Player1 => new Player1Actions(this);
    public interface IPlayerActions
    {
        void OnAxis(InputAction.CallbackContext context);
        void OnSouthButton(InputAction.CallbackContext context);
        void OnNorthButton(InputAction.CallbackContext context);
        void OnEastButton(InputAction.CallbackContext context);
        void OnWestButton(InputAction.CallbackContext context);
        void OnPause(InputAction.CallbackContext context);
        void OnRBumper(InputAction.CallbackContext context);
        void OnLBumper(InputAction.CallbackContext context);
        void OnRTrigger(InputAction.CallbackContext context);
        void OnLTrigger(InputAction.CallbackContext context);
    }
    public interface IPlayer1Actions
    {
        void OnAxis(InputAction.CallbackContext context);
        void OnSouthButton(InputAction.CallbackContext context);
        void OnNorthButton(InputAction.CallbackContext context);
        void OnEastButton(InputAction.CallbackContext context);
        void OnWestButton(InputAction.CallbackContext context);
        void OnPause(InputAction.CallbackContext context);
        void OnRBumper(InputAction.CallbackContext context);
        void OnLBumper(InputAction.CallbackContext context);
        void OnRTrigger(InputAction.CallbackContext context);
        void OnLTrigger(InputAction.CallbackContext context);
    }
}
